CREATE TABLE PRODUCT(
	NUM INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(20) NOT NULL,
	SUBTITLE VARCHAR(500) NOT NULL,
	COLOR VARCHAR(50) NOT NULL,
	PRICE INT DEFAULT 0,
	PIMG VARCHAR(500) NOT NULL
);