CREATE TABLE PRODUCT(
	PNUM INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(20) NOT NULL,
	PIMG VARCHAR(500) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	SUBTITLE VARCHAR(500) NOT NULL
);

DROP TABLE PRODUCT;

SELECT * FROM PRODUCT;

INSERT INTO PRODUCT(TITLE, PIMG, COUNTRY, SUBTITLE) VALUES("안녕", "안녕", "우크라이나", "안녕하세요");