CREATE TABLE REPLY(
	RNUM INT PRIMARY KEY AUTO_INCREMENT,
	MID VARCHAR(50) NOT NULL,
	BNUM INT NOT NULL,
	REPLY VARCHAR(500) NOT NULL,
	CONSTRAINT BOARD_REPLY FOREIGN KEY(BNUM) REFERENCES BOARD(BNUM) ON DELETE CASCADE
);

SELECT * FROM REPLY;